//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Video.rc
//
#define IDD_DIALOG1                     101
#define IDD_DIALOG2                     111
#define IDD_DIALOG3                     112
#define IDC_RESOLUTION_WINDOW_MODE      1000
#define IDC_RESOLUTION_FULL_SCREEN_MODE 1001
#define IDC_NEXT_TRI                    1002
#define IDC_NEXT_FLUSH                  1002
#define IDC_NEXT_FRAME                  1003
#define IDC_NEXT_DLIST                  1004
#define IDC_NEXT_MUX                    1005
#define IDC_DLIST_DEASSEMBLE            1006
#define IDC_LOG_OPCODE                  1006
#define IDC_LOG_UCODE                   1006
#define IDC_CLEAR                       1007
#define IDC_SET_BREAKPOINT              1008
#define IDC_MSG                         1009
#define IDC_BREAK_AT_MUX                1010
#define IDC_BREAK_AT_COUNT              1011
#define IDC_CLEAR_BREAKPOINT            1012
#define IDC_DLIST_COUNT                 1013
#define IDC_MUX_USAGE                   1014
#define IDC_LOG_COMBINERS               1014
#define IDC_UNKNOWN_MUX                 1015
#define IDC_PAUSE                       1016
#define IDC_GO                          1017
#define IDC_VI_REGS                     1018
#define IDC_COLORS                      1019
#define IDC_DUMP_VERTEX                 1020
#define IDC_NEXT_TRIANGLE               1021
#define IDC_NEXT                        1022
#define IDC_DUMP                        1023
#define IDC_TRI_DETAILS                 1024
#define IDC_LOG_TRIANGLES               1024
#define IDC_DETAILS_VERTEX_MTX          1025
#define IDC_LOG_VTX                     1025
#define IDC_LOG_MATRIX                  1026
#define IDC_WINFRAME                    1027
#define IDC_CULLFACE                    1028
#define IDC_ZBUFFER                     1029
#define IDC_ENABLE_TEXTURE              1030
#define IDC_TEST_TRIS                   1031
#define IDC_HACKS                       1032
#define IDC_DUMP_UNKNOWN_OPCODE         1033
#define IDC_LOG_UNKNOWN                 1033
#define IDC_LOG_WARNING                 1033
#define IDC_BLENDING                    1034
#define IDC_NORMAL_BLENDING             1034
#define IDC_TEX_PROCESS                 1035
#define IDC_LOG_TEXTURES                1035
#define IDC_NEXT_EVENT_TYPE             1036
#define IDC_THING_TO_DUMP               1037
#define IDC_DISABLE_BLENDING            1038
#define IDC_UPDATE_AT_CI_CHANGE         1040
#define IDC_CONT_W_UNKNOWN              1041
#define IDC_FAST_TEX_CRC                1042
#define IDC_SMART_UPDATE                1043
#define IDC_EMU_FRAME_BUFFER            1044
#define IDC_SMART_SCREEN_UPDATE         1045
#define IDC_BUFFER_TYPE                 1046
#define IDC_ALPHA_BLENDER               1047
#define IDC_DEPTH_BUFFER                1048
#define IDC_ENABLE_BG                   1049
#define IDC_LOG_SETTING                 1050
#define IDC_FRAME_BUFFER_SETTING        1051
#define IDC_UPDATE_SCREEN               1052
#define IDC_ACCURATE_TEXTURE_MAPPING    1053
#define IDC_DROP_TEXTURE                1054
#define IDC_SMART                       1055
#define IDC_DROP_COMBINER               1056
#define IDC_RENDER_ENGINE_SELECTION     1057
#define IDC_FOG                         1058
#define IDC_DX_COMBINER_SELECTION       1059
#define IDC_DISABLE_COMBINER            1060
#define IDC_SSE                         1061
#define IDC_SOFTWARE_CLIPPER            1062
#define IDC_SETTING_LABEL1              1063
#define IDC_SETTING_LABEL2              1064
#define IDC_SETTING_LABEL3              1065
#define IDC_FORCE_DEPTH_COMPARE         1066
#define IDC_SETTING_LABEL4              1067
#define IDC_TEXTURE_ENHANCEMENT         1068
#define IDC_FORCE_TEXTURE_FILTER        1069
#define IDC_TEXTURE_ENHANCEMENT_CONTROL 1070
#define IDC_FORCE_BUFFER_CLEAR          1071
#define IDC_OPTION_GROUP                1072
#define IDC_OPTION_GROUP2               1073
#define IDC_ABOUT                       1074
#define IDC_SCREEN_UPDATE_LABEL         1075
#define IDC_MORE_OPTIONS                1076
#define IDC_FULLSCREEN_FREQUENCY        1077
#define IDC_SOFTWARE_TNL                1078
#define IDC_EDIT_WIDTH                  1079
#define IDC_OGL_COMBINER                1080
#define IDC_DX_COMBINER                 1081
#define IDC_DX_SWAP_EFFECT              1082
#define IDC_COLOR_QUALITY               1083
#define IDC_SLIDER_FSAA                 1084
#define IDC_SLIDER_ANISO                1085
#define IDC_ANTI_ALIASING_TEXT          1086
#define IDC_ANISOTROPIC_TEXT            1087
#define IDC_ANISOTROPIC_MAX_TEXT        1088
#define IDC_ANTI_ALIASING_MAX_TEXT      1089
#define IDC_FULL_TMEM                   1090
#define IDC_EDIT_HEIGHT                 1091
#define IDC_TMEM_EMULATION_DEBUG        1092
#define IDC_NORMAL_COMBINER             1093
#define IDC_TEXTURE_1_HACK              1094
#define IDC_ALPHA_TEST                  1095
#define IDC_PRIMARY_DEPTH_HACK          1096
#define IDC_FASTER_LOADING_TILE         1097
#define IDC_TEXTURE_SCALE_HACK          1098
#define IDC_EMULATE_CLEAR               1099
#define IDC_TOOLTIP                     1100
#define IDC_DISABLE_BLENDER             1101
#define IDC_SKIP_FRAME                  1102
#define IDC_INCREASE_TEXTRECT_EDGE      1103
#define IDC_SKIP_FRAME2                 1104
#define IDC_FRAME_BUFFER_SETTING2       1105
#define IDC_SCREEN_UPDATE_AT            1106
#define IDC_DISABLE_BG                  1107
#define IDC_WINFRAME_MODE               1108
#define IDC_DISABLE_CULLING             1109
#define IDC_DISABLE_TEXTURE_CACHING     1110
#define IDC_TXTR_BUF_DOUBLE_SIZE        1111
#define IDC_SMALLER_TEXTURE             1111
#define IDC_RENDER_TO_TEXTURE_SETTING   1112
#define IDC_TEXTURE_QUALITY             1113
#define IDC_FRAME_BUFFER_WRITE_BACK_CONTROL 1114
#define IDC_LOG_TEXTURE_BUFFER          1115
#define IDC_LOG_BACK_BUFFER             1116
#define IDC_DX_DEVICE                   1117
#define IDC_DX_ADAPTER_TEXT             1118
#define IDC_DX_DEVICE_TEXT              1119
#define IDC_SHOW_FPS                    1120
#define IDC_FPS_COLOR                   1121
#define IDC_IN_N64_RESOLUTION           1122
#define IDC_SAVE_VRAM                   1123
#define IDC_AUTO_WRITE_BACK             1124
#define IDC_LABEL8                      1125
#define IDC_USE_CI_WIDTH_AND_RATIO      1126
#define IDC_TEXRECT_ONLY                1127
#define IDC_SMALL_TXT_ONLY              1128
#define IDC_HIDE_ADVANCED_OPTIONS       1129
#define IDC_LABEL5                      1130
#define IDC_LABEL6                      1131
#define IDC_LABEL7                      1132
#define IDC_TMEM                        1133
#define IDC_TXT_SIZE_METHOD_2           1134
#define IDC_LOG_TO_SCREEN               1134
#define IDC_ENABLE_LOD                  1135
#define IDC_LOG_TO_FILE                 1135
#define IDC_LOG_MICROCODE               1136
#define IDC_CHECK1                      1137
#define IDC_LOG_FOG                     1137
#define IDC_CHECK2                      1138
#define IDC_DETAILS                     1138

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        113
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1139
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
